### PR TITLE
add the aarches

### PR DESCRIPTION
**Pull request by mahf708**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mahf708** [comment]
@conda-forge-admin, please rerender

**Comment by mahf708** [comment]
The three nontraditional arches will likely work out-of-the-box, but confirming that won't be straightforward. I recommend we merge this and hope for the best. If someone reports issues, we can fix them. It is very likely that most users will use mpi_serial on linux_64 machines only anyway. Assigning to you @xylar and @zklaus. (@zklaus, feel free to cherry-pick this into the `mod` PR you have open if it is nearing completion, so that you won't bother with rebasing!)

**Review by xylar — APPROVED** [review]
I see.  I thought there would be a bunch of cross-compiling nonsense in the build section that I don't really understand.  Apparently not.

**Comment by xylar** [comment]
I think the `mod` PR is in already so that's not a concern.

**Comment by xylar** [comment]
@zklaus, please merge if you're happy.

**Comment by zklaus** [comment]
I think it's basically fine. Should we add `test: native_and_emulated`, though? And the bot seems to always add
```
provider:
  linux_aarch64: default
  linux_ppc64le: default
```

What do you think, @mahf708 ?

**Comment by mahf708** [comment]
> I think it's basically fine. Should we add `test: native_and_emulated`, though? And the bot seems to always add
> 
> ```
> provider:
>   linux_aarch64: default
>   linux_ppc64le: default
> ```
> 
> What do you think, @mahf708 ?

I think `default` will be fine too. I believe we are doing `linux_64` for now anyway. (We really don't want to open a can of worms with Travis...)

I'd be curious to see `test: native_and_emulated` fares, so:
1. I will add `test: native_and_emulated` and test
2. Then, I will add `default` and test

**Comment by mahf708** [comment]
I'd rather not specify the `provider` fields for now. Based on what I've seen of late, Travis is very annoying, and we likely don't need it.

**Pull request merged**
